# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1so5Fatw0R_Q_TckKhkoU9_a7zIQ6hJ8P
"""



"""## **Resume Chatbot using Image OCR**"""

!pip install langchain-core langchain-community langchain-text-splitters langchain-huggingface langchain-groq chromadb sentence-transformers pytesseract pillow
!apt-get install tesseract-ocr -y

from google.colab import files
uploaded = files.upload()

import os
import getpass
from PIL import Image
import pytesseract
from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser
from langchain_huggingface import HuggingFaceEndpoint, ChatHuggingFace

# 🔐 HuggingFace API
if "HUGGINGFACEHUB_API_TOKEN" not in os.environ:
    os.environ["HUGGINGFACEHUB_API_TOKEN"] = getpass.getpass("Enter Hugging Face Token: ")

# 🤖 LLM (Same as your YouTube bot)
hf_endpoint = HuggingFaceEndpoint(
    repo_id="Qwen/Qwen2.5-7B-Instruct",
    task="text-generation",
    max_new_tokens=512,
    temperature=0.1,
    do_sample=False
)

llm = ChatHuggingFace(llm=hf_endpoint)

# 🖼️ OCR SECTION
image_path = list(uploaded.keys())[0]
print("Reading Resume Image...")

img = Image.open(image_path)
extracted_text = pytesseract.image_to_string(img)

print("Extracted Text Length:", len(extracted_text))

# Convert to LangChain document
data = [Document(page_content=extracted_text)]

# ✂️ Text Split
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=150)
docs = text_splitter.split_documents(data)
print(f"Split transcript into {len(docs)} chunks.")

# 🧠 Embeddings
embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

# 🗂️ Store in Chroma
vectorstore = Chroma.from_documents(documents=docs, embedding=embeddings)

retriever = vectorstore.as_retriever(search_kwargs={"k": 3})

def format_docs(d):
    return "\n\n".join(doc.page_content for doc in d)

# 📝 Resume Prompt
template = """
You are an intelligent AI Resume Assistant.
Use the following resume content to answer professionally.
If information is not present, say you don't know.

Resume Content:
{context}

Question:
{question}
"""

prompt = ChatPromptTemplate.from_template(template)

rag_chain = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

print("✅ Resume Chatbot Ready!")

while True:
    question = input("🧑 Ask about the resume (type exit to quit): ")

    if question.lower() == "exit":
        break

    response = rag_chain.invoke(question)
    print("🤖:", response)
    print("-" * 50)